# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install flake8 pytest || true

      - name: Lint with flake8
        run: |
          flake8 . || true

      - name: Test with pytest (if tests present)
        run: |
          if ls **/test_*.py 1> /dev/null 2>&1; then pytest; else echo "No tests found, skipping."; fi

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Run mock federated learning round
        run: |
          python data/generate_dataset.py
          python backend/server.py &
          python clients/client_1/train.py &
          python clients/client_N/train.py &
          wait
      - name: Log training loop status
        run: |
          echo "[CI] Training loop status: completed (stub)" 